open source/config/routes.rb
# frozen_string_literal: true

require 'sidekiq_unique_jobs/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  root 'home#index'
  resources :apidocs, only: [:index]

  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  get 'health', to: 'health#show'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
  end

  namespace :oauth do
    scope :mfa do
      post :challenge, controller: 'mfa'
    end
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/change-password', to: redirect('/auth/edit')
  post '.well-known/skadnetwork/report-attribution/', to: 'well_known/skadnetwork#create'

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }
  get 'intent', to: 'intents#show'
  get 'custom.css', to: 'custom_css#show', as: :custom_css
  get '/unsubscribe', to: 'unsubscribe#unsubscribe'

  get '/link/:id', to: 'link#show', as: :link
  devise_scope :user do
    get '/invite/:invite_code', to: 'auth/registrations#new', as: :public_invite

    namespace :auth do
      resource :setup, only: [:show, :update], controller: :setup
      resource :challenge, only: [:create], controller: :challenges
      get 'sessions/security_key_options', to: 'sessions#webauthn_options'
    end
  end

  devise_for :users, path: 'auth', controllers: {
    omniauth_callbacks: 'auth/omniauth_callbacks',
    sessions: 'auth/sessions',
    registrations: 'auth/registrations',
    passwords: 'auth/passwords',
    confirmations: 'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: lambda { |req| req.format.nil? || req.format.html? }

  resources :accounts, path: 'users', only: [:show], param: :username do
    get :remote_follow, to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end

      resources :replies, only: [:index], module: :activitypub
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    resource :claim, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
    resource :followers_synchronization, only: [:show], module: :activitypub
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:username/with_replies', to: 'accounts#show', as: :short_account_with_replies
  get '/@:username/media', to: 'accounts#show', as: :short_account_media
  get '/@:username/tagged/:tag', to: 'accounts#show', as: :short_account_tag
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status
  get '/@:account_username/:id/embed', to: 'statuses#embed', as: :embed_short_account_status

  get '/interact/:id', to: 'remote_interaction#new', as: :remote_interaction
  post '/interact/:id', to: 'remote_interaction#create'

  get '/explore', to: 'directories#index', as: :explore
  get '/settings', to: redirect('/settings/profile')

  namespace :settings do
    resource :profile, only: [:show, :update] do
      resources :pictures, only: :destroy
    end

    get :preferences, to: redirect('/settings/preferences/appearance')

    namespace :preferences do
      resource :appearance, only: [:show, :update], controller: :appearance
      resource :notifications, only: [:show, :update]
      resource :other, only: [:show, :update], controller: :other
    end

    resource :import, only: [:show, :create]
    resource :export, only: [:show, :create]

    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
      resources :lists, only: :index, controller: :lists
      resources :domain_blocks, only: :index, controller: :blocked_domains
      resources :user_invites, only: :index
      resources :bookmarks, only: :index, controller: :bookmarks
    end

    resources :two_factor_authentication_methods, only: [:index] do
      collection do
        post :disable
      end
    end

    resource :otp_authentication, only: [:show, :create], controller: 'two_factor_authentication/otp_authentication'

    resources :webauthn_credentials, only: [:index, :new, :create, :destroy],
              path: 'security_keys',
              controller: 'two_factor_authentication/webauthn_credentials' do
      collection do
        get :options
      end
    end

    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :identity_proofs, only: [:index, :new, :create, :destroy]

    resources :applications, except: [:edit, :index] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]
    resource :migration, only: [:show, :create]

    namespace :migration do
      resource :redirect, only: [:new, :create, :destroy]
    end

    resources :aliases, only: [:index, :create, :destroy]
    resources :sessions, only: [:destroy]
    resources :featured_tags, only: [:index, :create, :destroy]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags, only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show, :index]
  resource :relationships, only: [:update]

  # get '/public', to: 'public_timelines#show', as: :public_timeline
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :domain_allows, only: [:new, :create, :show, :destroy]
    resources :domain_blocks, only: [:new, :create, :show, :destroy, :update, :edit]

    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]

    resources :announcements, except: [:show] do
      member do
        post :publish
        post :unpublish
      end
    end

    resource :settings, only: [:edit, :update]
    resources :site_uploads, only: [:destroy]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ } do
      member do
        post :clear_delivery_errors
        post :restart_delivery
        post :stop_delivery
      end
    end

    resources :rules

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :destroy] do
      member do
        post :enable
        post :unsensitive
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
        post :unverify
        post :bot
        post :unbot
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :relationships, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role, only: [] do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :ip_blocks, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]
    resource :follow_recommendations, only: [:show, :update]

    resources :tags, only: [:index, :show, :update] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  scope :_ma1sd do
    scope :backend do
      scope :api do
        scope :v1 do
          post '/auth/login', to: 'api/v1/ma1sd/authentication#auth'
          post '/directory/user/search', to: 'api/v1/ma1sd/directory#search'
          post '/identity/single', to: 'api/v1/ma1sd/identity#single'
          post '/identity/bulk', to: 'api/v1/ma1sd/identity#bulk'
          post '/profile/displayName', to: 'api/v1/ma1sd/profile#display_name'

open source/app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  PAGE_SIZE     = 20
  PAGE_SIZE_MAX = 200

  include AccountControllerConcern
  include SignatureAuthentication

  before_action :require_signature!, if: -> { request.format == :json && authorized_fetch_mode? }
  before_action :set_cache_headers
  before_action :set_body_classes

  skip_around_action :set_locale, if: -> { [:json, :rss].include?(request.format&.to_sym) }
  skip_before_action :require_functional!, unless: :whitelist_mode?

  def show
    respond_to do |format|
      format.html do
        expires_in 0, public: true unless user_signed_in?

        @pinned_statuses   = []
        @endorsed_accounts = @account.endorsed_accounts.to_a.sample(4)
        @featured_hashtags = @account.featured_tags.order(statuses_count: :desc)

        if current_account && @account.blocking?(current_account)
          @statuses = []
          return
        end

        @pinned_statuses = cache_collection(@account.pinned_statuses.merge!(StatusPin.profile_pins), Status) if show_pinned_statuses?
        @statuses        = cached_filtered_status_page
        @rss_url         = rss_url

        unless @statuses.empty?
          @older_url = older_url if @statuses.last.id > filtered_statuses.last.id
          @newer_url = newer_url if @statuses.first.id < filtered_statuses.first.id
        end
      end

      format.rss do
        expires_in 1.minute, public: true

        limit     = params[:limit].present? ? [params[:limit].to_i, PAGE_SIZE_MAX].min : PAGE_SIZE
        @statuses = filtered_statuses.without_reblogs.limit(limit)
        @statuses = cache_collection(@statuses, Status)
        render xml: RSS::AccountSerializer.render(@account, @statuses, params[:tag])
      end

      format.json do
        expires_in 3.minutes, public: !(authorized_fetch_mode? && signed_request_account.present?)
        render_with_cache json: @account, content_type: 'application/activity+json', serializer: ActivityPub::ActorSerializer, adapter: ActivityPub::Adapter
      end
    end
  end

  private

  def set_body_classes
    @body_classes = 'with-modals'
  end

  def show_pinned_statuses?
    [replies_requested?, media_requested?, tag_requested?, params[:max_id].present?, params[:min_id].present?].none?
  end

  def filtered_statuses
    default_statuses.tap do |statuses|
      statuses.merge!(hashtag_scope)    if tag_requested?
      statuses.merge!(only_media_scope) if media_requested?
      statuses.merge!(no_replies_scope) unless replies_requested?
    end
  end

  def default_statuses
    @account.statuses.where(visibility: [:public, :unlisted])
  end

  def only_media_scope
    Status.joins(:media_attachments).merge(@account.media_attachments.reorder(nil)).group(:id)
  end

  def no_replies_scope
    Status.without_replies
  end

  def hashtag_scope
    tag = Tag.find_normalized(params[:tag])

    if tag
      Status.tagged_with(tag.id)
    else
      Status.none
    end
  end

  def username_param
    params[:username]
  end

  def skip_temporary_suspension_response?
    request.format == :json
  end

  def rss_url
    if tag_requested?
      short_account_tag_url(@account, params[:tag], format: 'rss')
    else
      short_account_url(@account, format: 'rss')
    end
  end

  def older_url
    pagination_url(max_id: @statuses.last.id)
  end

  def newer_url
    pagination_url(min_id: @statuses.first.id)
  end

  def pagination_url(max_id: nil, min_id: nil)
    if tag_requested?
      short_account_tag_url(@account, params[:tag], max_id: max_id, min_id: min_id)
    elsif media_requested?
      short_account_media_url(@account, max_id: max_id, min_id: min_id)
    elsif replies_requested?
      short_account_with_replies_url(@account, max_id: max_id, min_id: min_id)
    else
      short_account_url(@account, max_id: max_id, min_id: min_id)
    end
  end

  def media_requested?
    request.path.split('.').first.end_with?('/media') && !tag_requested?
  end

  def replies_requested?
    request.path.split('.').first.end_with?('/with_replies') && !tag_requested?
  end

  def tag_requested?
    request.path.split('.').first.end_with?(Addressable::URI.parse("/tagged/#{params[:tag]}").normalize)
  end

  def cached_filtered_status_page
    cache_collection_paginated_by_id(
      filtered_statuses,
      Status,
      PAGE_SIZE,
      params_slice(:max_id, :min_id, :since_id)
    )
  end

  def params_slice(*keys)
    params.slice(*keys).permit(*keys)
  end
end

open source/app/controllers/api/pleroma/accounts_controller.rb
# frozen_string_literal: true
class Api::Pleroma::AccountsController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read }, only: [:mfa, :setup_totp, :backup_codes]
  before_action -> { doorkeeper_authorize! :write }, only: [:confirm_totp, :delete_totp]
  before_action :require_user!
  before_action :prepare_two_factor, only: [:setup_totp]
  before_action :validate_password, only: [:confirm_totp, :delete_totp]

  def mfa
    otp_enabled = current_user.otp_required_for_login

    render json: { settings: { enabled: otp_enabled, totp: otp_enabled } }
  end

  def setup_totp
    render json: { "key": @new_otp_secret, "provisioning_uri": @provision_uri }
  end

  def confirm_totp
    if current_user.validate_and_consume_otp!(resource_params[:code])
      current_user.otp_required_for_login = true
      current_user.save!

      UserMailer.two_factor_enabled(current_user).deliver_later!
    else
      render json: {"error": I18n.t('otp_authentication.wrong_code')}, status: 422
    end
  end

  def backup_codes
    @recovery_codes = current_user.generate_otp_backup_codes!

    if current_user.save!
      render json: { "codes": @recovery_codes }
    else
      render json: current_user.errors, status: 422
    end
  end

  def delete_totp
    current_user.otp_required_for_login = false
    current_user.otp_secret = nil
    current_user.save!
  end

  private

  def prepare_two_factor
    @new_otp_secret = User.generate_otp_secret(32)
    @provision_uri = current_user.otp_provisioning_uri(current_user.email,
                                                       otp_secret: @new_otp_secret,
                                                       issuer: Rails.configuration.x.local_domain)
    current_user.otp_secret = @new_otp_secret
    current_user.save!
  end

  def validate_password
    forbidden unless current_user.valid_password?(resource_params[:password])
  end

  def resource_params
    params.permit(:password, :code)
  end
end

open source/app/controllers/api/v1/accounts/featured_tags_controller.rb
# frozen_string_literal: true

class Api::V1::Accounts::FeaturedTagsController < Api::BaseController
  before_action :set_account
  before_action :set_featured_tags

  respond_to :json

  def index
    render json: @featured_tags, each_serializer: REST::FeaturedTagSerializer
  end

  private

  def set_account
    @account = Account.find(params[:account_id])
  end

  def set_featured_tags
    @featured_tags = @account.suspended? ? [] : @account.featured_tags
  end
end

open source/app/controllers/api/v1/accounts/identity_proofs_controller.rb
# frozen_string_literal: true

class Api::V1::Accounts::IdentityProofsController < Api::BaseController
  before_action :require_user!
  before_action :set_account

  def index
    @proofs = @account.suspended? ? [] : @account.identity_proofs.active
    render json: @proofs, each_serializer: REST::IdentityProofSerializer
  end

  private

  def set_account
    @account = Account.find(params[:account_id])
  end
end

open source/app/views/accounts/_bio.html.haml
- proofs = account.identity_proofs.active
- fields = account.fields

.public-account-bio
  - unless fields.empty? && proofs.empty?
    .account__header__fields
      - proofs.each do |proof|
        %dl
          %dt= proof.provider.capitalize
          %dd.verified
            = link_to fa_icon('check'), proof.badge.proof_url, class: 'verified__mark', title: t('accounts.link_verified_on', date: l(proof.updated_at))
            = link_to proof.provider_username, proof.badge.profile_url

      - fields.each do |field|
        %dl
          %dt.emojify{ title: field.name }= Formatter.instance.format_field(account, field.name, custom_emojify: true)
          %dd{ title: field.value, class: custom_field_classes(field) }
            - if field.verified?
              %span.verified__mark{ title: t('accounts.link_verified_on', date: l(field.verified_at)) }
                = fa_icon 'check'
            = Formatter.instance.format_field(account, field.value, custom_emojify: true)

  = account_badge(account)

  - if account.note.present?
    .account__header__content.emojify= Formatter.instance.simplified_format(account, custom_emojify: true)

  .public-account-bio__extra
    = t 'accounts.joined', date: l(account.created_at, format: :month)

open source/app/views/accounts/_header.html.haml
.public-account-header{:class => ("inactive" if account.moved?)}
  .public-account-header__image
    = image_tag (prefers_autoplay? ? account.header_original_url : account.header_static_url), class: 'parallax'
  .public-account-header__bar
    = link_to short_account_url(account), class: 'avatar' do
      = image_tag (prefers_autoplay? ? account.avatar_original_url : account.avatar_static_url), id: 'profile_page_avatar', data: { original: full_asset_url(account.avatar_original_url), static: full_asset_url(account.avatar_static_url), autoplay: prefers_autoplay? }
    .public-account-header__tabs
      .public-account-header__tabs__name
        %h1
          = display_name(account, custom_emojify: true)
          %small
            = acct(account)
            = fa_icon('lock') if account.locked?
      .public-account-header__tabs__tabs
        .details-counters
          .counter{ class: active_nav_class(short_account_url(account), short_account_with_replies_url(account), short_account_media_url(account)) }
            = link_to short_account_url(account), class: 'u-url u-uid', title: number_with_delimiter(account.statuses_count) do
              %span.counter-number= number_to_human account.statuses_count, strip_insignificant_zeros: true
              %span.counter-label= t('accounts.posts', count: account.statuses_count)

          .counter{ class: active_nav_class(account_following_index_url(account)) }
            = link_to account_following_index_url(account), title: number_with_delimiter(account.following_count) do
              %span.counter-number= number_to_human account.following_count, strip_insignificant_zeros: true
              %span.counter-label= t('accounts.following', count: account.following_count)

          .counter{ class: active_nav_class(account_followers_url(account)) }
            = link_to account_followers_url(account), title: number_with_delimiter(account.followers_count) do
              %span.counter-number= number_to_human account.followers_count, strip_insignificant_zeros: true
              %span.counter-label= t('accounts.followers', count: account.followers_count)
        .spacer
        .public-account-header__tabs__tabs__buttons
          = account_action_button(account)

    .public-account-header__extra
      = render 'accounts/bio', account: account

      .public-account-header__extra__links
        = link_to account_following_index_url(account) do
          %strong= number_to_human account.following_count, strip_insignificant_zeros: true
          = t('accounts.following', count: account.following_count)
        = link_to account_followers_url(account) do
          %strong= number_to_human account.followers_count, strip_insignificant_zeros: true
          = t('accounts.followers', count: account.followers_count)

open source/app/views/accounts/_moved.html.haml
- moved_to_account = account.moved_to_account

.moved-account-widget
  .moved-account-widget__message
    = fa_icon 'suitcase'
    = t('accounts.moved_html', name: content_tag(:bdi, content_tag(:strong, display_name(account, custom_emojify: true), class: :emojify)), new_profile_link: link_to(content_tag(:strong, safe_join(['@', content_tag(:span, moved_to_account.acct)])), ActivityPub::TagManager.instance.url_for(moved_to_account), class: 'mention'))

  .moved-account-widget__card
    = link_to ActivityPub::TagManager.instance.url_for(moved_to_account), class: 'detailed-status__display-name p-author h-card', target: '_blank', rel: 'me noopener noreferrer' do
      .detailed-status__display-avatar
        .account__avatar-overlay
          .account__avatar-overlay-base
            = image_tag moved_to_account.avatar_static_url
          .account__avatar-overlay-overlay
            = image_tag account.avatar_static_url

      %span.display-name
        %bdi
          %strong.emojify= display_name(moved_to_account, custom_emojify: true)
        %span @#{moved_to_account.acct}

open source/app/views/accounts/_og.html.haml
- description = account_description(account)

%meta{ name: 'description', content: description }/

= opengraph 'og:url', url
= opengraph 'og:site_name', site_title
= opengraph 'og:title', yield(:page_title).strip
= opengraph 'og:description', description
= opengraph 'og:image', full_asset_url(account.avatar.url(:original))
= opengraph 'og:image:width', '400'
= opengraph 'og:image:height', '400'
= opengraph 'twitter:card', 'summary'
= opengraph 'profile:username', acct(account)[1..-1]

open source/app/views/accounts/show.html.haml
- content_for :page_title do
  = "#{display_name(@account)} (#{acct(@account)})"

- content_for :header_tags do
  - if @account.user&.setting_noindex
    %meta{ name: 'robots', content: 'noindex, noarchive' }/

  %link{ rel: 'alternate', type: 'application/rss+xml', href: @rss_url }/
  %link{ rel: 'alternate', type: 'application/activity+json', href: ActivityPub::TagManager.instance.uri_for(@account) }/

  - if @older_url
    %link{ rel: 'next', href: @older_url }/
  - if @newer_url
    %link{ rel: 'prev', href: @newer_url }/

  = opengraph 'og:type', 'profile'
  = render 'og', account: @account, url: short_account_url(@account, only_path: false)


= render 'header', account: @account, with_bio: true

.grid
  .column-0
    .h-feed
      %data.p-name{ value: "#{@account.username} on #{site_hostname}" }/

      .account__section-headline
        = active_link_to t('accounts.posts_tab_heading'), short_account_url(@account)
        = active_link_to t('accounts.posts_with_replies'), short_account_with_replies_url(@account)
        = active_link_to t('accounts.media'), short_account_media_url(@account)

      - if user_signed_in? && @account.blocking?(current_account)
        .nothing-here.nothing-here--under-tabs= t('accounts.unavailable')
      - elsif @statuses.empty?
        = nothing_here 'nothing-here--under-tabs'
      - else
        .activity-stream.activity-stream--under-tabs
          - if params[:page].to_i.zero?
            = render partial: 'statuses/status', collection: @pinned_statuses, as: :status, locals: { pinned: true }

          - if @newer_url
            .entry= link_to_newer @newer_url

          = render partial: 'statuses/status', collection: @statuses, as: :status

          - if @older_url
            .entry= link_to_older @older_url

  .column-1
    - if @account.memorial?
      .memoriam-widget= t('in_memoriam_html')
    - elsif @account.moved?
      = render 'moved', account: @account

    = render 'bio', account: @account

    - if @endorsed_accounts.empty? && @account.id == current_account&.id
      .placeholder-widget= t('accounts.endorsements_hint')
    - elsif !@endorsed_accounts.empty?
      .endorsements-widget
        %h4= t 'accounts.choices_html', name: content_tag(:bdi, display_name(@account, custom_emojify: true))

        - @endorsed_accounts.each do |account|
          = account_link_to account

    - else
      - @featured_hashtags.each do |featured_tag|
        .directory__tag{ class: params[:tag] == featured_tag.name ? 'active' : nil }
          = link_to short_account_tag_path(@account, featured_tag.tag) do
            %h4
              = fa_icon 'hashtag'
              = featured_tag.name
              %small
                - if featured_tag.last_status_at.nil?
                  = t('accounts.nothing_here')
                - else
                  %time.formatted{ datetime: featured_tag.last_status_at.iso8601, title: l(featured_tag.last_status_at) }= l featured_tag.last_status_at
            .trends__item__current= number_to_human featured_tag.statuses_count, strip_insignificant_zeros: true

    -# = render 'application/sidebar'